service:
  AppMode: debug
  HttpPort: :3000

db_type: mysql
mysql:
  Db: mysql
  DbHost: 127.0.0.1
  DbPort: 3306
  DbUser: root
  DbPassWord: root
  DbName: micro_todolist
  MysqlTimeout: 10s
  MysqlLifeTimeout: 28700
  MysqlMaxOpenCons:   100
  MysqlMaxIdleCons:   100
etcd:
  registryAddr: 127.0.0.1:2379
gateway:
  addr: 127.0.0.1:4000
  protocol: http
servers:
  gateway:
  userServer:
    address: 127.0.0.1:8082